### PR TITLE
Add poem found online

### LINKED ISSUE #13: Review New Poem
Please review my pull request.

### PR DESCRIPTION
**Pull request by aaron4careset**
Added new poem from Aaron.

### CODE REVIEW

**Review by ftrotter — CHANGES_REQUESTED** [review]
This is great!! But what we really need is also a limerick. Can you add one?

**Comment by aaron4careset** [comment]
Just added a Limerick

**Review by ftrotter — APPROVED** [review]
brilliant!!

**Comment by ftrotter** [comment]
go ahead and merge the pull request in and delete the branch!!

**Pull request merged**
