### PR TITLE
Create irene_poem.md

### PR DESCRIPTION
**Pull request by IreneVarghese**
Added Irene's haiku. Please Approve.

### CODE REVIEW

**Review by ftrotter — CHANGES_REQUESTED** [review]
What is really needed here is a "limerick"... can you add one?

**Comment by IreneVarghese** [comment]
Added a limerick. Please Review.

**Review by ftrotter — APPROVED** [review]

**Comment by ftrotter** [comment]
Looks great!! Go ahead and merge the pull request and then delete the working branch!!!

**Comment by IreneVarghese** [comment]
Merged the pull request and deleted the branch.

**Pull request merged**
