### PR TITLE
Added new poem

### PR DESCRIPTION
**Pull request by almirmav**
Added new poem for exercise. Please review my collaboration poem and merge it to main branch.

### CODE REVIEW

**Review by ftrotter — CHANGES_REQUESTED** [review]
Hey Almir.. what this branch really needs is the addition of a limerick! Does that work?

**Comment by almirmav** [comment]
@ftrotter do you prefer additional limerick in the same file or separated?

**Comment by almirmav** [comment]
@ftrotter Limerick was added. Please review.

**Review by ftrotter — APPROVED** [review]

**Comment by ftrotter** [comment]
great go ahead and merge this branch and delete it!!

**Pull request merged**
